package model;

public enum EventType {
    BID_CREATED,
    BID_CLOSEDDOWN,
    BID_NEWRESPONSE,
    CONTRACT_ADD,
    CONTRACT_TERMINATE,
    CONTRACT_PATCH,
    DISPUTE_ADD,
    DISPUTE_RESOLVE,
    CONTRACT_REUSE
}
