package model;

public enum EventType {
    BID_ADD,
    BID_PATCH,
    BID_CLOSEDOWN,
    BID_BUYOUT,
    CONTRACT_ADD,
    CONTRACT_TERMINATE,
    CONTRACT_PATCH,
    DISPUTE_ADD,
    DISPUTE_RESOLVE,
    CONTRACT_REUSE
}
