package model;

public enum EventType {
    BID_CREATED,
    BID_CLOSEDDOWN,
    BID_NEWRESPONSE,
    MESSAGE_PATCH,
    CONTRACT_CREATE,
    CONTRACT_TERMINATE,
    CONTRACT_PATCH,
    DISPUTE_ADD,
    DISPUTE_RESOLVE
}
